version: '3.9'

services:
  apache-php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apache-php-container
    ports:
      - "80:80"  # HTTP
    volumes:
      - ./index.html:/var/www/html/index.html
      - ./script.js:/var/www/html/script.js
      - ./style.css:/var/www/html/style.css
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
